const types = {
    CHANGE_TITLE: "CHANGE_TITLE",
    WITH_PARAMS: "WITH_PARAMS",
    VALUE: "VALUE",
    ADD_USER: "ADD_USER",
    DELETE_ALL_USERS: "DELETE_ALL_USERS",
    CLEAR_NUMBERS: "CLEAR_NUMBER",
    ADD_NUMBER: "ADD_NUMBER"
};

export default types;
export const ADD_NUMBER = 'ADD_NUMBER';
export const CLEAR_NUMBERS = 'CLEAR_NUMBERS';


